description:
  Sample config for Voronoi diagram generation (case_8).

voronoi:
  width: 3072
  height: 2048
  output_dir: ./outputs/sample_case_8
  
  # Seed point generation settings (random or poisson_disk)
  point_generation:
    # method: "random"
    # params:
    #   points_num: [1943, 1269, 882, 660, 522, 415, 338, 287, 241, 203, 175, 159, 140, 126, 110, 98, 92, 82, 77, 73, 66, 62, 59, 54, 51]

    method: "poisson_disk"
    params:
      min_distance: [40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280]
      max_attempts: 100

  # Drawing settings
  label_info:
    color: [255, 255, 255]
    thickness: 2
  
  image_info: # uniform or gaussian
    # method: "uniform"

    method: "gaussian"
    params:
      mean: 128
      std: 32
  
  # Post-processing processor settings
  post_processors:
    - type: "crop"
      apply_to: "both"
      params:
        crop_width: 2560
        crop_height: 1536
    # - type: "elliptical_mask"
    #   apply_to: "image"
    #   params:
    #     min_num: 0
    #     max_num: 10
    #     min_size: 10
    #     max_size: 40
    #     color: [0, 0, 0]
    - type: "gaussian_noise"
      apply_to: "image"
      params:
        mean: 0
        std: 20
    # - type: "perlin_noise"
    #   apply_to: "image"
    #   params:
    #     res: [32, 32]
    #     noise_range: 20
  
  datatype_info:
    train:
      diagram_num: 10
      seed: 0
    valid:
      diagram_num: 10
      seed: 1
  
  split:
    split_width: 512
    split_height: 512 